### ISSUE TITLE
WebDriverError: Connection refused (Connection refused)

### ISSUE THREAD

**Issue by pudgereyem** [topheman/react-es6-redux#18]
Hey dude!

When I run `npm run test e2e` I get the error `WebDriverError: Connection refused (Connection refused)`. Do you know why?

Thanks!

**Comment by topheman** [comment]
Thank you for the report! I fixed the bug which was due to the version of webdriver which wasn't working anymore with the latest version of chrome (most likely v56).

I found the [chromedriver](https://www.npmjs.com/package/chromedriver) npm package which lets you point protractor to a specific version of webdriver (that will be ok for the moment. In the futur, protractor should be upgraded from v3 to latest v5).

I had the same bug on an other project of mine [topheman/vanilla-es6-jspm](https://github.com/topheman/vanilla-es6-jspm) which I hadn't spotted! So thank you very much for your report.
